### ISSUE TITLE
Change JsonViewTest to read from configuration

### ISSUE THREAD

**Issue by AmaliaMV** [grails/grails-views#144]
I have a custom base template class called example.ExampleJsonView

```
grails:
    views:
          json:
              mimeTypes:
                - application/json
                - application/hal+json
              compileStatic: true
              baseTemplateClass: example.ExampleJsonView
```
This class has a method which is called in a json view.

```
package example

import grails.plugin.json.view.JsonViewWritableScript

abstract class ExampleJsonView extends JsonViewWritableScript {
    def myMethod(String a) {
        return "Message $a"
    }
}
```

This is my json view: /example/index
```
json {
    attra "view index attra"
    attrb "view index attrb"
    message myMethod("hello")
}
```
When I run the app, this works fine. But, when I want to run following test I have problems.

```
class ExampleJsonViewSpec extends Specification implements JsonViewTest {

    void "Test render GSON view"() {

        when: "A gson view is rendered"

        JsonRenderResult result = render(view: "example/index.gson")

        then: "The json is correct"
        result.json["message"] == "Message hello"
    }
}
```

```
Condition not satisfied:

result.json["message"] == "Message hello"
|      |   |           |
|      |   null        false
|      [attra:view index attra, attrb:view index attrb, myMethod:hello, message:null]
grails.plugin.json.view.test.JsonRenderResult(200, OK, null, [:], [attra:view index attra, attrb:view index attrb, myMethod:hello, message:null], {"attra":"view index attra","attrb":"view index attrb","myMethod":"hello","message":null})

Expected :Message hello

Actual   :null
```

This is the link to the example app: https://github.com/AmaliaMV/gson-view-inherits
