### ISSUE TITLE
ContentType is text/html in 1.1.2

### ISSUE THREAD

**Issue by andreasschiestl** [grails/grails-views#93]
After Upgrading from 1.1.1 to 1.1.2 our application didn't longer work. The issue was that the content type was `text/html` instead of `application/json` and was no longer handled correct at the client side.

we tried to set the mime type with:
```
grails:
    views:
        json:
            mimeTypes:
              - application/json
```

but this was not working, server still returning `text/html` as content type
