### ISSUE TITLE
Gradle plugin: "baseTemplateClass" setting is ignored when "compileGsonViews" is executed

### ISSUE THREAD

**Issue by shushkevich** [grails/grails-views#98]
When app defines custom template class as follows:
```
grails:
    views:
        json:
            baseTemplateClass: com.example.MyCustomJsonViewTemplate
```

then it works fine if you run application with `grails run-app`, but if you will create a war file, then gson files will be precompiled by using default JsonViewTemplate class, i.e. `baseTemplateClass` setting is not taken into account.
